### ISSUE TITLE
[Bug] Unable to connect to CoopNet

### ISSUE THREAD

**Issue by rWiiolU** [coop-deluxe/sm64coopdx#732]
Ok, I want to start this off by saying that I was able to play CoopNet a couple weeks ago, but now I just can't connect online. I have done many things including: going into the files, seeing if I got banned (which I didn't, I don't get the banned message). Strangely, I can still see the rooms, I just can't join them. I don't get an error, I just get stuck on the joining screen until I click Cancel.
**To Reproduce**
Steps to reproduce the behavior (note I don't know how this happened but this is just a guess):
1. Download sm64coopdx for Mac ARM
2. Click on 'Join' and click on any room.
3. You shouldn't be able to join.

**Expected behavior**
Able to join rooms.

**Screenshots**
Here's a picture of where I get stuck at:

![Image](https://github.com/user-attachments/assets/20639eae-a9ed-44e2-94aa-75c2c6f82b3c)

**Desktop (please complete the following information):**
 - OS: Mac Sequoia 15.3.2
 - Browser: Google Chrome
 - Version 1.3

**Additional context**
I have no clue why the online doesn't work for me anymore, it worked perfectly fine before. I really don't know how to fix this issue.

**Comment by rWiiolU** [comment]
Note: I can still host games

**Comment by frog8412** [comment]
> Note: I can still host games

Since people are able to join your lobbies, that means the person you're connecting has some internet issues

**Comment by rWiiolU** [comment]
I don't think people can join my games, and its every game that I try joining.

**Comment by rWiiolU** [comment]
If you want me to make a room just to be sure just let me know, my username in coopdx is rWiiolU, same as my GitHub one

**Comment by rWiiolU** [comment]
AND it seems like it was a completed issue, so I am really confused as of why mine is still bugged 😭

**Comment by EmeraldLoc** [comment]
This is an issue exclusive to macOS. The reason this happens is unknown, and is being investigated.

**Comment by rWiiolU** [comment]
I think it might have to do something with ARM macs, but it could also be Intel macs

**Comment by frog8412** [comment]
> If you want me to make a room just to be sure just let me know, my username in coopdx is rWiiolU, same as my GitHub one

lol the thing is I also can't connect to coopnet, i am from russia and it seems like all russians have issues connecting to coopnet

**Comment by rWiiolU** [comment]
People can still see the rooms that I host, yet I don't know if they can join. I literally downloaded 2 coopdx games btw

![Image](https://github.com/user-attachments/assets/f754f4a0-965b-40d6-b2f7-6d7128efdd46)

**Comment by rWiiolU** [comment]
> > lol the thing is I also can't connect to coopnet, i am from russia and it seems like all russians have issues connecting to coopnet

oh welp guess i gotta wait to play hide and seek dx some more, and so do a lot of people as well. hopefully this gets fixed at like 1.3.1 or 1.4

**Comment by rWiiolU** [comment]
Maybe its how the thing finds mods to be sure that all mods that the host has is downloaded? I'm not sure though.

**Comment by rWiiolU** [comment]
Maybe you updated the mod site and it somehow broke joining on macOS

**Comment by rWiiolU** [comment]
> > Maybe you updated the mod site and it somehow broke joining on macOS, it doesn't give an ETA. 

Scratch that, it might have to do with something else.
It probably has to do something with finding mods. It disconnects me from servers when the room is full. And when it isn't, the 2 bars aren't going, they just don't do anything. Of course, take your time, I just miss playing online with others.

**Comment by PolarHacker** [comment]
I'm on a M-Series Mac too. Tried both the ARM and Intel apps, same issue. Looks like the issue should be fixed with version 1.3.1, due at the end of the month, based on what I see on Discord :)

<img width="596" alt="Image" src="https://github.com/user-attachments/assets/a2fcc7c3-f64e-4674-b731-ce566249ff30" />

**Comment by rWiiolU** [comment]
Yippee!!! That's tomorrow!

**Comment by rWiiolU** [comment]
It's still not fixed for me, I tired joining a lobby and waiting for like 2 minutes and it didn't show an ETA!

![Image](https://github.com/user-attachments/assets/695049dd-6552-4fb2-9bd5-0e26b1a6bd43)

(Can't send video to prove, I'm (kinda) to mac, sorry!)

**Comment by AgentXLP** [comment]
Fixed in 1.3.2, coming soon

**Comment by PolarHacker** [comment]
Tested 1.3.2 on my Mac, all seems well now! Thank you :)
